#ifndef __CONFIG_ZYNQ_RC_H
#define __CONFIG_ZYNQ_RC_H

#define CONFIG_SYS_SDRAM_SIZE		(1024 * 1024 * 1024)

#define CONFIG_ZYNQ_SERIAL_UART1
#define CONFIG_ZYNQ_GEM0
#define CONFIG_ZYNQ_GEM_PHY_ADDR0	7

#define CONFIG_SYS_NO_FLASH
#define CONFIG_SPI_FLASH_MACRONIX	1

#define CONFIG_ZYNQ_SDHCI0
#define CONFIG_ZYNQ_SDHCI1
#define CONFIG_ZYNQ_USB
#define CONFIG_ZYNQ_QSPI
#define CONFIG_ZYNQ_I2C0
#define CONFIG_ZYNQ_EEPROM
#define CONFIG_ZYNQ_BOOT_FREEBSD
#define CONFIG_DEFAULT_DEVICE_TREE	zynq-zc702

#define CONFIG_CMD_SETEXPR
#define CONFIG_CMD_STRSTR	/* STRSTR utility			*/

#include <configs/zynq-common.h>

#define CONFIG_CMD_MEMTEST
#define CONFIG_SYS_ALT_MEMTEST
#define CONFIG_SYS_MEMTEST_START	CONFIG_SYS_SDRAM_BASE
#define CONFIG_SYS_MEMTEST_END		(CONFIG_SYS_SDRAM_BASE + CONFIG_SYS_SDRAM_SIZE - 4)
#define CONFIG_SYS_MEMTEST_SCRATCH  (CONFIG_SYS_MEMTEST_END - 4)

#endif /* __CONFIG_ZYNQ_RC_H */
